username: stickerlight
app-id: com.instagram.android
use-cloned-app: false
allow-untested-ig-version: true
screen-sleep: false
screen-record: false
speed-multiplier: 2
close-apps: true
kill-atx-agent: false
restart-atx-agent: true
disable-block-detection: false
disable-filters: false
dont-type: false
total-crashes-limit: 4
count-app-crashes: false
shuffle-jobs: true
truncate-sources: 2-5
debug: true

## Interaction (active jobs)
blogger-followers: [denindjofficial, ranedj, nativeinstruments, djtechtools, djcity, beatsourceofficial, numark_dj, infinityfaders, heavyhitspool, 12inchskinz, customlitt, pioneerdjglobal, pioneerdjeurope, Mojaxx]
# hashtag-likers-top: []
feed: 3-5

## Special modifier for jobs and sources
watch-video-time: 3-35
watch-photo-time: 3-6
delete-interacted-users: true

## Unfollow (unfollow jobs)
# unfollow-any: 2-4
# unfollow: 3-7

## Special modifier for unfollow jobs
# sort-followers-newest-to-oldest: true
# unfollow-delay: 30

## Remove followers
delete-removed-followers: true

## Post Processing
telegram-reports: true

interactions-count: 50-80
likes-count: 2-4
likes-percentage: 80
stories-count: 1-3
stories-percentage: 80-95
carousel-count: 1-2
carousel-percentage: 40-50
max-comments-pro-user: 0
comment-percentage: 0
pm-percentage: 100
interact-percentage: 85
follow-percentage: 50-80
follow-limit: 20-60
skipped-list-limit: 10-15
skipped-posts-limit: 5
fling-when-skipped: 0
min-following: 100

total-likes-limit: 50-80
total-follows-limit: 20-60
# total-unfollows-limit: 1-4
total-watches-limit: 25-40
total-successful-interactions-limit: 60-120
total-interactions-limit: 60-120
total-comments-limit: 0
total-pm-limit: 2-5
total-scraped-limit: 50-100

end-if-likes-limit-reached: true
end-if-follows-limit-reached: false
end-if-watches-limit-reached: false
end-if-comments-limit-reached: false
end-if-pm-limit-reached: false

# working-hours: [10.15-16.40, 18.15-22.46]
# time-delta: 15-20
# repeat: 200-260
total-sessions: -1