stories-count: null
likes-count: 1-2
carousel-count: null
unfollow-any-non-followers: null
igbot-follow-auto-increment-enabled: true
unfollow-any: null
igbot-template-like-methods:
- blogger-followers
delete-interacted-users: null
follow-percentage: '1'
follow-limit: 5-10
total-unfollows-limit: '10'
end-if-follows-limit-reached: null
total-likes-limit: '20'
igbot-like-auto-increment-by: '2'
igbot-follow-auto-increment-maximum: '20'
total-comments-limit: null
unfollow-delay: '3'
end-if-likes-limit-reached: null
delete-removed-followers: null
comment-percentage: null
igbot-dm-budget: 5-10
min-following: null
watch-video-time: 2-3
sort-followers-newest-to-oldest: null
igbot-unfollow-auto-increment-maximum: '20'
igbot-dm-method: new-followers
max-comments-pro-user: null
total-watches-limit: null
igbot-follow-only-active-stories: false
unfollow: null
unfollow-any-followers: null
total-pm-limit: '10'
total-follows-limit: '10'
unfollow-non-followers: null
igbot-unfollow-method: search
igbot-unfollow-sort: default
igbot-like-budget: 5-10
igbot-unfollow-auto-increment-by: '2'
igbot-unfollow-auto-increment-enabled: true
stories-percentage: null
likes-percentage: '100'
watch-photo-time: 1-2
igbot-like-action-delay: '0'
igbot-dm-action-delay: '0'
end-if-watches-limit-reached: null
igbot-follow-auto-increment-by: '2'
igbot-like-auto-increment-maximum: '30'
pm-percentage: '1'
igbot-unfollow-budget: 5-10
end-if-comments-limit-reached: null
carousel-percentage: null
end-if-pm-limit-reached: null
igbot-unfollow-enabled: true
igbot-follow-mute-after-follow: true
igbot-template-follow-methods:
- blogger-followers
igbot-unfollow-action-delay: '0'
igbot-like-auto-increment-enabled: true
